# Generated by Django 3.2.4 on 2021-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_adult',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price for adult'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_children',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price for children'),
        ),
    ]
