# Generated by Django 3.2.4 on 2021-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211108_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='qty_adult',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='qty_children',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
