# Generated by Django 3.2.4 on 2021-11-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211112_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='for_anonymous_user',
            field=models.BooleanField(default=False, verbose_name='AnonymousUser'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='qty_adult',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='qty_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
