# Generated by Django 3.2.4 on 2021-11-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_cartproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='pub_date',
        ),
    ]
