# Generated by Django 3.2.4 on 2021-12-31 15:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211231_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Imagine')),
                ('pub_date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('price_adult', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price for adult')),
                ('price_children', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Price for children')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=255, verbose_name='Status is order')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.country', verbose_name='Country')),
            ],
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Name product'),
        ),
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
