# Generated by Django 4.0.1 on 2022-03-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20211231_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Name ppp'),
        ),
    ]
